import ch.so.agi.gretl.tasks.Publisher

apply plugin: 'ch.so.agi.gretl'

tasks.register('publish', Publisher) {
    outDataIdent = 'ch.so.agi.publisher.xtf-regex'
    outFolderPath = file("$buildDir/local")
    outWriteMetadata = false
    xtfFile_FolderPath = file('.').absolutePath
    xtfFilename_Regex = 'SimpleCoord23[ab]\\.xtf'
    customModelDir = file('.').absolutePath
    outFormats = ['xtf']
}
