apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: gretl-platform
metadata:
  creationTimestamp: null
  name: gretl-platform
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: gretl
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: sogis/gretl:${GRETL_IMAGE_TAG}
      name: latest
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
parameters:
- name: GRETL_IMAGE_TAG
  description: GRETL image tag to be pulled from Docker Hub.
  displayName: GRETL image tag
  value: latest
- name: IMPORT_POLICY_SCHEDULED
  description: Regularly check for changed image
  value: "false"
