apiVersion: v1
kind: ConfigMap
data:
  ORG_GRADLE_PROJECT_dbUriEdit: jdbc:postgresql://localhost/edit?sslmode=require&ApplicationName=GRETL
  ORG_GRADLE_PROJECT_dbUriPub: jdbc:postgresql://localhost/pub?sslmode=require&ApplicationName=GRETL
  ORG_GRADLE_PROJECT_ili2dbModeldir: '%ILI_FROM_DB;%XTF_DIR;https://geo.so.ch/models/;%JAR_DIR'
  ORG_GRADLE_PROJECT_ilivalidatorModeldir: '%ITF_DIR;https://geo.so.ch/models/;%JAR_DIR/ilimodels'
  ORG_GRADLE_PROJECT_geoservicesHostName: geo-t.so.ch
  ORG_GRADLE_PROJECT_gretlEnvironment: test
metadata:
  labels:
    app: gretl-platform
  name: gretl-resources
