apiVersion: v1
kind: Template
labels:
  app: gretl-platform
metadata:
  creationTimestamp: null
  name: gretl-platform
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: gretl
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: sogis/gretl-runtime:${GRETL_RUNTIME_IMAGE_TAG}
      name: latest
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
parameters:
- name: GRETL_RUNTIME_IMAGE_TAG
  description: Docker image tag of GRETL runtime to be pulled from Docker Hub.
  displayName: Docker image tag of GRETL runtime
  value: latest
- name: IMPORT_POLICY_SCHEDULED
  description: Regularly check for changed image
  value: "false"
