apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: gretl-platform
metadata:
  creationTimestamp: null
  name: gretl-platform
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: jenkins-agent
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/openshift/origin-jenkins-agent-base:${JENKINS_AGENT_IMAGE_TAG}
      name: latest
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
parameters:
- name: JENKINS_AGENT_IMAGE_TAG
  description: Docker image tag of Jenkins agent to be pulled from external registry
  displayName: Docker image tag of Jenkins agent
  value: latest
- name: IMPORT_POLICY_SCHEDULED
  description: Regularly check for changed image
  value: "false"
