apiVersion: v1
kind: Template
metadata:
  name: gretl-dockerhub-is-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: gretlout
    name: gretlout
  spec:
    nodeSelector: null
    output:
      pushSecret:
        name: dockerhub
      to:
        kind: DockerImage
        name: docker.io/${GRETL_DOCKER_HUB_IMAGE}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: FROM centos:7
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: '${GRETL_RUNTIME_IMAGESTREAM}'
      type: Docker
    triggers: []
parameters:
  - name: GRETL_DOCKER_HUB_IMAGE
    displayName: Docker Hub image of GRETL runtime
    description: Docker Hub image repo, name and version of builded docker image.
    value: sogis/gretl-runtime:latest
    required: true
  - name: GRETL_RUNTIME_IMAGESTREAM
    displayName: GRETL runtime imagestream
    description: GRETL runtime imagestream name and tag (of build project).
    value: gretl:latest
    required: true
