#!/bin/sh

run_parameter="$@"

if [ -f /home/gradle/build.info ]; then
    cat /home/gradle/build.info
fi

gradle $run_parameter \
       --init-script /home/gradle/init.gradle \
       --gradle-user-home /home/default/.gradle \
       --stacktrace \
       --no-daemon
