import ch.so.agi.gretl.tasks.*

apply plugin: 'ch.so.agi.gretl'

def dbUri = findProperty('gretltest_dburi_pg') ?: 'jdbc:postgresql://localhost:5432/gretl'

defaultTasks 'importSchema'

tasks.register('importSchema', Ili2pgImportSchema) {
    database = [dbUri, 'ddluser', 'ddluser']
    models = 'SO_AGI_Publisher_Meta_20260623'
    def modelDirectory = file("$buildDir/models")
    modeldir = modelDirectory.absolutePath + ';https://models.interlis.ch/'
    dbschema = 'publisher_meta'
    createBasketCol = true

    doFirst {
        modelDirectory.mkdirs()
        [
            'https://geo.so.ch/models/AGI/SO_AGI_Publisher_Meta_20260623.ili',
            'https://models.geo.admin.ch/CH/CHBase_Part1_GEOMETRY_V2.ili'
        ].each { modelUrl ->
            new URL(modelUrl).withInputStream { input ->
                new File(modelDirectory, modelUrl.tokenize('/').last()).withOutputStream { output ->
                    output << input
                }
            }
        }
    }
}
